### ISSUE TITLE
GPU settings for longformer classification

### ISSUE THREAD

**Issue by jonas-nothnagel** [allenai/longformer#151]
Hi fellow transformer fans!

Can anyone share what GPU set-up (perhaps on a cloud provider) they used for successfully using longformer for classification. I always ran out of memory (OOM) when setting the max sequence higher than 1024. 

I tried very small batch sizes on single P4000+, but without success.

Thank you!

**Comment by ibeltagy** [comment]
you should be able to run longformer-base with seqlen ~4k on this gpu using batchsize=1, fp16, and gradient checkpointing

**Comment by jonas-nothnagel** [comment]
Thank you! Takes a long time, but it works with batch size 1.

**Comment by aditya-malte** [comment]
Hi @ibeltagy,
I have two questions:
I’d like to ask what would be the general GPU memory requirement for a generic document classification/regression task using Longformer (base) with around 3k to 4k max seq length and 32 batch size.

Also, I’d like to ask you that while you do suggest batch size as 1 (rather than say 32), does it produce usable models? I would assume keeping such a low batch size results in noisy gradients. Would be very happy to know if it is otherwise. (Same question to @jonas-nothnagel if you were able to train it successfully on batch size one) 

Thanks in advance.

**Comment by matt-peters** [comment]
Regarding batch size and training: use gradient accumulation up to effective batch size of 32 across multiple GPUs or on a single GPU before applying an optimizer update. There is a flag in pytorch lightning that enables this functionality.

**Comment by aditya-malte** [comment]
Hi @matt-peters,
I know how to enable gradient accumulation, but that doesn’t answer the questions I’ve asked. Specifically, I’m trying to understand the minimum setup that would be required to finetune Longformer based on the said batch size and sequence length.
Thanks

**Comment by matt-peters** [comment]
I'm not sure if any available GPU would be able to fit 32 sequences with length 4K into memory for training.  We haven't tried it.  However, by enabling gradient accumulation, the effective batch size (32) and performance remain unchanged, independent of the number of sequences processed at a time.  The response to the original question confirms it's possible to run longformer base on a GPU with 8GB RAM with one sequence in memory, so I'd guess that's the minimum setup.
