### ISSUE TITLE
sliding_chunks vs tvm in terms of speed

### ISSUE THREAD

**Issue by sarvghotra** [allenai/longformer#42]
Hi there,

Thanks for the great work and making code available.

I ran Longformer on TriviaQA dev set as per instructions given in cheatsheet (to reproduce leaderboard numbers with pretrained model) in "tvm" and then in "sliding_chunks" to compare their speed. I found that sliding_chunks mode is faster compared to "tvm" + fp32 and at par with "tvm " + fp16.

BTW, I was able to reproduce TriviQA metric numbers.

Could you please answer the following questions:

1. I thought "tvm" was supposed to be faster since its custom CUDA Kernal. Am I missing something?

     - Follow  up, If they both are equally fast then I wonder why does one need this CUDA kernal for window attention only (assuming one doesn't need dilation and autoregressive attention)

2. I thought "tvm" CUDA Kernal didn't support fp16 then how does the code runs fine with fp16 in "tvm" mode?

**Comment by ibeltagy** [comment]
Great question, thanks @sarvghotra. 

> I thought "tvm" was supposed to be faster since its custom CUDA Kernal. Am I missing something?


Here's time/memory comparison of three different implementations of the sliding window attention. `loop` and `tvm` are mentioned in the paper, and `chunks` is new.
![image](https://user-images.githubusercontent.com/2287797/82927687-ed355580-9f35-11ea-9fae-d279e4e5bd62.png)

- `loop` and `tvm` are the most memory-efficient because they compute only the nonzero values

- `chunks` uses 2x more memory because it computes many nonzero values then mask them out. It is still linear though

- `tvm` is as fast as `full`, which is not as fast as it should be. This is because our kernel is not super optimized as the standard nvidia matrix multiplication

- `chunks` is faster than `tvm` despite the fact that it computes 2x non-zero values because, again, it uses the standard matrix multiplication, which nvidia has been optimizing for years

Overall, if you need dilation or you want the most memory efficient implementation (this needs new `tvm` binaries that support fp16), use `tvm` otherwise, use `chunks`

> I thought "tvm" CUDA Kernal didn't support fp16 then how does the code runs fine with fp16 in "tvm" mode?

Check the code [here](https://github.com/allenai/longformer/blob/master/longformer/longformer.py#L146), we convert everything to fp32 before calling the `tvm` code then convert it back to fp16. If you are interested, you can try to compile the kernel for fp16 and add it. It

**Comment by sarvghotra** [comment]
Thanks for the detailed answer. Appreciate it.
