### ISSUE TITLE
Longformer Memory Consumption query

### ISSUE THREAD

**Issue by PrudhviRaj12** [allenai/longformer#96]
Hello,
Apologies if I am misunderstanding it, but if I use roberta with a max sequence length of 256 and I can run, for example, say, a batch size of 64 on one gpu for a task, with the longformer, can I use the same batch size with a window length of 256 with the max sequence length being 4096?

**Comment by ibeltagy** [comment]
No. 
roberta (seqlen: 256, bsz: 64) is processing 256 x 64 tokens while longformer (seqlen: 4096, window size: 256, bsz: 64) is processing 4096 x 64 tokens. Even if the attention cost is negligible (you can control it by changing window size), you still need memory to store activations for everything else. 

roberta (seqlen: 256, bsz: 64) is comparable to (seqlen: 4096, window size: 256, bsz: 4) because number of tokens per batch is the same.

**Comment by ibeltagy** [comment]
Closing. Please feel free to reopen if needed.
